### ISSUE TITLE
Repository update still at 0.3.1

### ISSUE THREAD

**Issue by aas88keyz** [logi85/plugin.video.flix2kodi#10]
When attempting to manually install from repository newest available to me is 0.3.1. When installing from github resolved my installation issue with 0.3.4.

**Comment by logi85** [comment]
I tried to install via repo, got 0.3.4 . please go to addon-folder and look for *flix*. If there is still a version, remove old stuff. then install via repository.

**Comment by aas88keyz** [comment]
Success after purging the plug in and repository and reinstalling both. The plugin successfully installed from the repo. looking good.
