### ISSUE TITLE
0.4.1 Crashes on login with credential message.

### ISSUE THREAD

**Issue by jwhite** [logi85/plugin.video.flix2kodi#15]
Log is here : 

12:09:14 T:140505035368192  NOTICE: [plugin.video.flix2kodi] Loading netflix: https://www.netflix.com/Login?locale=en-US Post: {u'RememberMe': u'on', u'authURL': '1451776099124.kICVTJDbT9XikXzf7aPzJc5H0Lc=', u'password': 'xxxxxx', u'email': 'xxxxxxxxxxxxx'}
12:09:17 T:140505035368192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/addon.py", line 89, in <module>
                                                if login.login()==True:
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/login.py", line 38, in login
                                                generic_utility.set_setting('api_url', match[0])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by logi85** [comment]
hi, please try again with 0.4.2, if not working, please go to https://www.netflix.com (logged in) with your browser and upload the source-code.

**Comment by jwhite** [comment]
Still not working.  I'm out of the house today but will try to check out the source tonight.

It has an identical error in the log.

**Comment by logi85** [comment]
Hi, just go to page and use 'view source' in browser and paste the content somewhere. I think the structure of the page is a little different perhaps land specific

**Comment by jwhite** [comment]
FWIW - I'm in New Zealand but using a DNS proxy to access the US account.  Tomorrow I'll find the source.

**Comment by logi85** [comment]
hi, any updates?

**Comment by jwhite** [comment]
Here are the two files.  One is where I am looking at the different people/users (3 squares)
The one called Netflix_Loggedin is where I am looking at the movies and have selected one of the 3 accounts.

[Netflix Login.zip](https://github.com/logi85/plugin.video.flix2kodi/files/80755/Netflix.Login.zip)

**Comment by logi85** [comment]
in the new version (0.4.8) I addded debug logging so if no apiurl will be found the whole response will be logged to logfile. please enable debug (in kodi and in addon settings) and try again and upload the log.
I'll release 0.4.8 in a few minutes/hours

**Comment by logi85** [comment]
released.

**Comment by jwhite** [comment]
14:23:18 T:140632613951232  NOTICE: [plugin.video.flix2kodi] Loading netflix: https://www.netflix.com/Login?locale=en-US Post: {u'RememberMe': u'on', u'authURL': '1451776099124.kICVTJDbT9XikXzf7aPzJc5H0Lc=', u'password': 'xxxxxx', u'email': 'xxxxxx'}
14:23:21 T:140632613951232  NOTICE: [plugin.video.flix2kodi] parameters: ?mode=main&thumb&type=movie&url
14:23:21 T:140632613951232   ERROR: [plugin.video.flix2kodi] Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/addon.py", line 84, in <module>
                                                handle_request()
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/addon.py", line 36, in handle_request
                                                general.main(video_type)
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/general.py", line 40, in main
                                                add_dynamic_lists(video_type)
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/general.py", line 30, in add_dynamic_lists
                                                content = connect.load_netflix_site("https://www.netflix.com/")
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/connect.py", line 110, in load_netflix_site
                                                if do_login():
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/connect.py", line 188, in do_login
                                                return login.login()
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/login.py", line 32, in login
                                                post=post_data, login_process=True)
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/connect.py", line 120, in load_netflix_site
                                                raise ValueError('!HTTP-ERROR!: '+str(status_code)+' loading: "'+url+'", post: "'+ str(post)+'"')
                                            ValueError: !HTTP-ERROR!: 200 loading: "https://www.netflix.com/Login?locale=en-US", post: "{u'RememberMe': u'on', u'authURL': '1451776099124.kICVTJDbT9XikXzf7aPzJc5H0Lc=', u'password': 'xxxxxx', u'email': 'xxxxxx'}"
14:23:26 T:140632613951232  NOTICE: [plugin.video.flix2kodi] Loading netflix: https://www.netflix.com/Login Post: None
14:23:28 T:140632613951232  NOTICE: [plugin.video.flix2kodi] Loading netflix: https://www.netflix.com/Login?locale=en-US Post: {u'RememberMe': u'on', u'authURL': '1451776099124.kICVTJDbT9XikXzf7aPzJc5H0Lc=', u'password': 'xxxxxx', u'email': 'xxxxxx'}
14:23:30 T:140632613951232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: !HTTP-ERROR!: 200 loading: "https://www.netflix.com/Login?locale=en-US", post: "{u'RememberMe': u'on', u'authURL': '1451776099124.kICVTJDbT9XikXzf7aPzJc5H0Lc=', u'password': 'xxxxxx', u'email': 'xxxxxx'}"
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/addon.py", line 91, in <module>
                                                if connect.do_login()==True:
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/connect.py", line 188, in do_login
                                                return login.login()
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/login.py", line 32, in login
                                                post=post_data, login_process=True)
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/connect.py", line 120, in load_netflix_site
                                                raise ValueError('!HTTP-ERROR!: '+str(status_code)+' loading: "'+url+'", post: "'+ str(post)+'"')
                                            ValueError: !HTTP-ERROR!: 200 loading: "https://www.netflix.com/Login?locale=en-US", post: "{u'RememberMe': u'on', u'authURL': '1451776099124.kICVTJDbT9XikXzf7aPzJc5H0Lc=', u'password': 'xxxxxx', u'email': 'xxxxxx'}"
                                            -->End of Python script error report<--
14:23:30 T:140634114238464   ERROR: GetDirectory - Error getting plugin://plugin.video.flix2kodi/?mode=main&thumb&type=movie&url
14:23:30 T:140634114238464   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.flix2kodi/?mode=main&thumb&type=movie&url) failed

**Comment by DCYeahThatsMe** [comment]
+1  I'm having the same issue...  v0.4.8 gives me the "Flix2Kodi crashed.  Try to refresh your login?"  

[flix2kodi-log.txt](https://github.com/logi85/plugin.video.flix2kodi/files/82994/flix2kodi-log.txt)

**Comment by logi85** [comment]
please upgrade to 0.4.9 and try again.

**Comment by jwhite** [comment]
Logging in works after getting the 'refresh your login' message.  I'll test out the rest of the functionality today.

**Comment by logi85** [comment]
Fine

**Comment by jwhite** [comment]
Everything working so far on my end.  I think this can be closed.
