### ISSUE TITLE
Using kodibuntu you will experience tearing without a compositing window manager

### ISSUE THREAD

**Issue by jwhite** [logi85/plugin.video.flix2kodi#16]
I suggest adding this line to the /usr/bin/kodi-standalone and then starting openbox:

<b>compton --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc --shadow-exclude "! name~=''" -b &
openbox &</b>

APP=Kodi
prefix="/usr"

Note : There is probably a better place to put this as it will be overwritten by the next kodi update.

I suggest adding this to a readme somewhere.

**Comment by logi85** [comment]
Hi, now there is a better place. Please have a look to the forum ( custom scripts ).
It would be great if you write a before_playback.sh and after_playback.sh so I'll integrate them as examples.

**Comment by jwhite** [comment]
Cool.  Sounds good.  I'll take a look

**Comment by logi85** [comment]
added to faq.
