### ISSUE TITLE
No playback occurs after selection

### ISSUE THREAD

**Issue by benno1973** [logi85/plugin.video.flix2kodi#17]
When selecting a movie or tv show to play back, the screen flashes up as though it is about to play something, but nothing plays and it then returns to the list of shows.

Currently occurring in 0.4.1

Log:

[kodi_log.txt](https://github.com/logi85/plugin.video.flix2kodi/files/76477/kodi_log.txt)

**Comment by logi85** [comment]
hi, please try again with 0.4.2

**Comment by benno1973** [comment]
Awesome, seems to work for me at the moment! Thanks for that...

**Comment by logi85** [comment]
you're welcome
