### ISSUE TITLE
Kore remote input does nothing once playback starts

### ISSUE THREAD

**Issue by mdmallardi** [logi85/plugin.video.flix2kodi#2]
In netflixbmc, Kore's (The official Kodi remote Android app) input at least could pause and close  the video even though the standard play controls did not come up.  In this plugin, the kore app cannot be used to control playback at all.

**Comment by logi85** [comment]
Have you tried the newest version? I just downloaded kore from play-store and can use the arrows to skip, the middle-button to pause/resume and the back key to close video.

**Comment by mdmallardi** [comment]
Sadly no.  Just tried with the latest HEAD commit, Kore does nothing while playing under Kodibuntu.

**Comment by logi85** [comment]
xdotool is installed? Something in logfile?

**Comment by mdmallardi** [comment]
xdotool is installed.  Nothing about keypresses in the logfile.

**Comment by logi85** [comment]
Do you have a running window manager? So that kodi is not launched as xsession?

**Comment by mdmallardi** [comment]
I have a running window manager, yes.  (openbox)  I believe that kodi is
run as an xsession, but I've modified the kodi-standalone script that's
invoked to launch it to start up openbox as part of it -- As mentioned,
this worked fine under netflixbmc, so I have all the prerequisites.

On Wed, Dec 23, 2015 at 10:51 AM, logi85 <notifications@github.com> wrote:

> Do you have a running window manager? So that kodi is not launched as
> xsession?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logi85/plugin.video.netflix/issues/2#issuecomment-166929335>
> .
>



-- 
Malcolm D. Mallardi

**Comment by logi85** [comment]
Is the window appearing in kodi while playing?  (... push back to go back...)

**Comment by logi85** [comment]
perhaps you could paste the modifications

**Comment by mdmallardi** [comment]
bin_name=kodi
APP="${bindir}/${bin_name} --standalone $@"
+
+/usr/bin/openbox &
+/usr/bin/devmon &

PULSE_START="$(which start-pulseaudio-x11)"
if [ -n "$PULSE_START" ]; then


On Wed, Dec 23, 2015 at 11:04 AM, logi85 <notifications@github.com> wrote:

> perhaps you could paste the modifications
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logi85/plugin.video.netflix/issues/2#issuecomment-166932054>
> .
>



-- 
Malcolm D. Mallardi

**Comment by logi85** [comment]
Hi,

I don't see the launch of kodi in your script. But you can try launching kodi after openbox is launched without --standalone , perhaps this helps.

**Comment by logi85** [comment]
Hi,

please try again with newest version.
If you press a key that the addon cannot interpret, it should be logged into logfile.
So please have a look into logfile after pressing the missing key and tell me which is missing.

**Comment by mdmallardi** [comment]
I'll test it thoroughly on the 2nd. I'm away until then.

**Comment by logi85** [comment]
@mdmallardi is it working for you with version 0.3.2?

**Comment by mdmallardi** [comment]
This is still not working for me.

On Fri, Jan 1, 2016 at 6:36 PM, logi85 <notifications@github.com> wrote:

> @mdmallardi <https://github.com/mdmallardi> is it working for you with
> version 0.3.2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logi85/plugin.video.flix2kodi/issues/2#issuecomment-168350717>
> .
>



-- 
Malcolm D. Mallardi

**Comment by logi85** [comment]
hi, if playback starts, is there a window containing: 'Push BACK to go back. If your browser not launches, something went wrong.' if you switch back to kodi while playback is running?

please provide a current log of the playback.

**Comment by mdmallardi** [comment]
There is no such window.

http://pastebin.com/NLNVQkHW -- Log from a current playback session

On Sat, Jan 2, 2016 at 12:37 PM, logi85 <notifications@github.com> wrote:

> hi, if playback starts, is there a window containing: 'Push BACK to go
> back. If your browser not launches, something went wrong.' if you switch
> back to kodi while playback is running?
>
> please provide a current log of the playback.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logi85/plugin.video.flix2kodi/issues/2#issuecomment-168411682>
> .
>



-- 
Malcolm D. Mallardi

**Comment by logi85** [comment]
sorry I can not help without logfile.

**Comment by mdmallardi** [comment]
I linked a pastebin to the log.

On Sun, Jan 3, 2016 at 8:42 AM, logi85 <notifications@github.com> wrote:

> sorry I can not help without logfile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logi85/plugin.video.flix2kodi/issues/2#issuecomment-168499690>
> .
>



-- 
Malcolm D. Mallardi

**Comment by logi85** [comment]
sorry, but where is the link? I cannot find :)

**Comment by mdmallardi** [comment]
http://pastebin.com/NLNVQkHW -- Looks like it was hidden as an email quote a few comments back.

**Comment by mdmallardi** [comment]
I think this should be reopened.  I think the pastebin of that log has a limit of one week.  If necessary when you get around to looking at this, I'll get a new log up there.

**Comment by logi85** [comment]
hi, saw your log, please enable debug in addon settings and try again and post a new log. thx

**Comment by mdmallardi** [comment]
Will do so this evening.

On Tue, Jan 5, 2016 at 4:20 PM, logi85 <notifications@github.com> wrote:

> hi, saw your log, please enable debug in addon settings and try again and
> post a new log. thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logi85/plugin.video.flix2kodi/issues/2#issuecomment-169137248>
> .
>



-- 
Malcolm D. Mallardi

**Comment by logi85** [comment]
thx, sounds funny 'this evening' ;-) here in germany it is 22:22 now. where are you?

**Comment by mdmallardi** [comment]
East coast USA, it's 16:41 here at the moment.  I should be home in about
two hours.

On Tue, Jan 5, 2016 at 4:22 PM, logi85 <notifications@github.com> wrote:

> thx, sounds funny 'this evening' ;-) here in germany it is 22:22 now.
> where are you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logi85/plugin.video.flix2kodi/issues/2#issuecomment-169137726>
> .
>



-- 
Malcolm D. Mallardi

**Comment by logi85** [comment]
ok so we have an one-day-gap.

**Comment by mdmallardi** [comment]
http://pastebin.com/ge916a3L

I'm still not seeing anything about unknown keys or anything.

**Comment by logi85** [comment]
pastebin seems to be expired.. but if the window in kodi will not come up, it cannot capture the keys/actions. please try to call the launch script with an url as parameter ( chrome.sh http://google.com ).
It should launch chrome with google and should stay blocked until you close chrome. if it not stay blocked you have to add something to wait for the process to terminate. in my version it's included.

**Comment by mdmallardi** [comment]
I think you are misunderstanding the situation -- Chrome launches.  The video plays.  Kore apparently still passes through to Kodi and not to Chrome (Though the keyboard does pass through to chrome)  It in fact also allows me to start a second instance of chrome (Which, looking at the chrome script, shouldn't be possible)

**Comment by mdmallardi** [comment]
How odd, suddenly it started working (The warning about the browser not launching came up, and kore's actions went to chrome.)  all I can think that I did was switch profiles,

**Comment by mdmallardi** [comment]
I figured out the problem -- The plugin doesn't block input and handle key events if the stream is started by using the play option from the information screen (I had 'Show Information' as my default action on videos)  I switched that to Play and suddenly things worked.  I do still consider this a regression, as NetfliXBMC's kore support worked from either screen.

**Comment by logi85** [comment]
I think this could be a kodi problem. just tired with kore and Kodi 17.0 Alpha 1(03.01.2016). However, will close this issue, until someone else has same problems. you could try to user Kodi 17 to see if it's version-specific, if you want to.
