### ISSUE TITLE
"Can't update playcount..." error

### ISSUE THREAD

**Issue by benno1973** [logi85/plugin.video.flix2kodi#22]
When returning from watching a TV show, Flix2Kodi shows an error message 'Cannot update playcount...'. This only occurs when items exist in %appdata%\Kodi\userdata\addon_data\plugin.video.flix2kodi\library with a single apostrophe ('). When these items are removed, the issue is resolved and no longer occurs.

Running Kodi 15.2 on Win 7 SP1. Error log:

[Flix2Kodi_CannotUpdatePlaycountCrash.txt](https://github.com/logi85/plugin.video.flix2kodi/files/80720/Flix2Kodi_CannotUpdatePlaycountCrash.txt)

**Comment by logi85** [comment]
hi, should now be fixed. was a windows-only problem

**Comment by logi85** [comment]
closed after ~2 weeks no reply
