### ISSUE TITLE
Feature Request: Extract ID from file content instead of file name

### ISSUE THREAD

**Issue by horstepipe** [logi85/plugin.video.flix2kodi#28]
hey
for scraping and renaming junkies like me it would be great to see if Flix2Kodi could (optionally) extract the movie/episode ID from the file content instead of the file name. Thus we could realize a consistent naming of all files and don't have to exclude the Flix2Kodi files from the auto-renamer

**Comment by logi85** [comment]
hi, I don't see any possibility to do that. Just modified flix2kodi to use the database for searching and updating playcounts. I need the video-id from netflix to do that. On the other hand I cannot set the video-id in the database cause there is no possibility to do that. With the current solution there is no need to access the filesystem and there should be no need to do this. I think the best solution would be to exclude *.strm files from auto-renamer. This is the regexp I use to filter: "\.V(.*)V\.strm"
Sorry.
