### ISSUE TITLE
Flix2Kodi on OSMC

### ISSUE THREAD

**Issue by mircobabini** [logi85/plugin.video.flix2kodi#29]
It doesn't work as-is.

I managed to get it work by doing:
`sudo apt-get install python-pip python-dev`
`sudo apt-get install autoconf g++`
`sudo pip install pycrypto`

Cheers, great job!

**Comment by mircobabini** [comment]
Maybe it would be easier with:
`sudo apt-get install python-crypto`

**Comment by logi85** [comment]
closed cause already in faq (forum, 3. post)
