### ISSUE TITLE
Crashes with error 'Flix2Kodi crashed: Try to refresh your login' 

### ISSUE THREAD

**Issue by sarhugo** [logi85/plugin.video.flix2kodi#33]
Hi, after login I try to go to movies, tv shows or suggestions and I get 'Flix2Kodi crashed: Try to refresh your login'.
On logs I found:

`
20:26:46 T:140634853721856  NOTICE: [plugin.video.flix2kodi] Loading netflix: https://www.netflix.com/api/shakti/6c589cb5/pathEvaluator?materialize=true&model=harris Post: {"paths":[["lolomos","Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_ROOT","mylist"],["lolomos","Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_ROOT",{"from":0,"to":99},"displayName"]],"authURL":"1457392779728.Gz43XnpDlCdFedFoyE/g3pN6F6k="}
20:26:47 T:140634853721856  NOTICE: [plugin.video.flix2kodi] parameters: ?mode=main&thumb&type=dynamic&url
20:26:47 T:140634853721856   ERROR: [plugin.video.flix2kodi] Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.flix2kodi/addon.py", line 85, in <module>
                                                handle_request()
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.flix2kodi/addon.py", line 37, in handle_request
                                                general.main(video_type)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.flix2kodi/resources/general.py", line 43, in main
                                                add_dynamic_lists()
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.flix2kodi/resources/general.py", line 58, in add_dynamic_lists
                                                mylist_id, lists = lolomos.read_lists(ret, root_list)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.flix2kodi/resources/path_evaluator/types/lolomos.py", line 17, in read_lists
                                                mylist = child('mylist', rlst)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.flix2kodi/resources/path_evaluator/__init__.py", line 63, in child
                                                raise ValueError(str(chld)+' not found in: '+str(jsn))
                                            ValueError: mylist not found in: {u'24': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183180'], u'25': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183247'], u'26': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14184601'], u'27': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183193'], u'20': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14184052'], u'21': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183161'], u'22': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183165'], u'23': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183169'], u'28': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183611'], u'29': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183234'], u'0': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183175'], u'4': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183173'], u'8': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183188'], u'3': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183764'], u'7': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183174'], u'33': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183766'], u'32': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14185095'], u'31': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183294'], u'30': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183198'], u'37': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183201'], u'36': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183170'], u'35': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14185146'], u'34': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14170041'], u'2': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14750553'], u'6': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183179'], u'11': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14186126'], u'10': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183178'], u'13': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183625'], u'12': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183181'], u'15': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183197'], u'14': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14184527'], u'17': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183321'], u'16': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183190'], u'19': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183177'], u'18': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183176'], u'1': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183187'], u'5': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14170035'], u'9': [u'lists', u'Fallback_LOLOMO_AR_harris_kidsfalse_en_ADULTS_14183171']}
`

For tv shows the mylist not found changes to $type not found.

**Comment by mdmallardi** [comment]
I too have been experiencing this behaviour as well.

**Comment by talondnb** [comment]
Same here.

**Comment by logi85** [comment]
should be fixed with 0.5.8

**Comment by sarhugo** [comment]
Thx, it works.

**Comment by infomate** [comment]
Tried it with the new 0.6.0 and it still crashes.....:(
