### ISSUE TITLE
Cannot login again

### ISSUE THREAD

**Issue by bhaal2** [logi85/plugin.video.flix2kodi#45]
Flix2kodi cannot login..  It's getting a 404 error:

ValueError: !HTTP-ERROR2!: 404 loading: "https://www.netflix.com/api/shakti72729320/profiles/switch?switchProfileGuid=xxxxxxxxxxxxxxxxxxxxxxx&authURL=xxxxxxxxxxxxxxxxxxxxx", post: "None"

**Comment by logi85** [comment]
merged. will upload in a few hours. thx to fkmclane!

**Comment by bhaal2** [comment]
Thanks fkmclane and logi85!

**Comment by bhaal2** [comment]
Seems to be working well now!
