### ISSUE TITLE
Fix for current breakage

### ISSUE THREAD

**Issue by polarathene** [logi85/plugin.video.flix2kodi#61]
Not a user yet, but came across [this discussion at page 58](http://forum.kodi.tv/showthread.php?tid=254263&page=58), on page 59 a user mentions a fork by `un5ki11ed` that has implemented fixes but not done a PR to merge them back yet.

[This commit](https://github.com/un5ki11ed/plugin.video.flix2kodi/commit/f3950044bb9d37ccef502a23a7c01ec3c10d3102), plus [this bugfix commit](https://github.com/un5ki11ed/plugin.video.flix2kodi/commit/6b43d2f2ade2c5727221f49faa88903068d11e7f) directly after should get the plugin working again.

**Comment by paskal** [comment]
I've opened #63 and suggest to close this one.
