### ISSUE TITLE
"Invalid Forum" error on installation instructions

### ISSUE THREAD

**Issue by jleaders** [logi85/plugin.video.flix2kodi#72]
There should be instructions to install in the Readme.md. 

Instead I Just get a link to a forum that when clicked says "Invalid Forum" 

This may be fixed if I create an account but I shouldn't have to do this to install an addon.

**Comment by Thrilleratplay** [comment]
I think the Kodi forum for April Fools was reverted to be XMBC again with none of the previous threads available.

**Comment by logi85** [comment]
Thx, fixed.
