### ISSUE TITLE
v0.3.2 playback does not work with chrome launcher 

### ISSUE THREAD

**Issue by macauleyr4** [logi85/plugin.video.flix2kodi#8]
I just installed v0.3.2 and no longer get playback when I select a video. I'm using openelec and chrome launcher. The chromelauncher.sh script does work when called manually from the console using the same path found in the addon [Log.](http://sprunge.us/BHgO)

**Comment by logi85** [comment]
ok i think i've found the problem. please try again with 0.3.3

**Comment by macauleyr4** [comment]
That fixed it. Thanks.

**Comment by logi85** [comment]
you're welcome ;-)
