### ISSUE TITLE
My List does not contain selections

### ISSUE THREAD

**Issue by aas88keyz** [logi85/plugin.video.flix2kodi#9]
When selecting the My List folder in either TV or Movies there is nothing in them. No videos or any other items. Was working before I installed 0.3.2 off github as the repository only has 0.3.1 available for update. First time submiting issue in github but I cannot upload *.log or *.zip. So don't know how to help.

**Comment by logi85** [comment]
hi, please try to update to 0.3.4, just fixed a related issue. You can force update on system->addons-> install from repository->selecting logi85... and in context menu 'check for updates'.
don't know if it works if you installed from github directly. perhaps you should uninstall the addon and install from repository again.

**Comment by aas88keyz** [comment]
Working even after login refresh error. Clean reinstall of plugin.
